### ISSUE TITLE
Update the ReadMe File

### ISSUE THREAD

**Issue by honeycoder96** [DSC-Galgotias/TechnoJam-Chat#1]
Add more details to the readme file about the Hackoctober Fest ,Developer Student Club, TechnoJam and Galgotias University.

Please dont forget to follow the [Contributors File](https://github.com/DSC-Galgotias/TechnoJam-Chat/blob/master/contributors.md)

**Comment by LiamBailey** [comment]
Hi @honeycoder96 

How many words would you be looking for on each of the 4items?

**Comment by honeycoder96** [comment]
hi @LiamBailey ,

Thanks for your interest ;)

We are just looking a well organized readme and contributors file so only very basic details will do.
Also i am attaching some links that will help you find the details about there.

1. [Galgotias University](http://galgotiasuniversity.edu.in)
2. [TechnoJam](https://www.facebook.com/technojam-scse)
3. [Hackoctoberfest](https://hacktoberfest.digitalocean.com/)
4. [Developers Student Club](https://developers.google.com/training/programs/india/)
5. [DSC Galgotias](https://github.com/DSC-Galgotias)

Once again thanks for your interest :100:
