### ISSUE TITLE
Password Characteristics

### ISSUE THREAD

**Issue by honeycoder96** [DSC-Galgotias/TechnoJam-Chat#19]
Current Behaviour: When user signup any password of length greater then 6 is accepted.

Expected Behaviour: Ask the user to input password in the following format

1. At least 1 special character, alphabet, number.
2. Length greater than 6.

Also, display help dialog as the user is about to input the password to tell the user the format of password expected.

If the password is not in that format display a snackbar(or toast) to notify the user the missing characteristic, ie. If special character, a number is missing or length is less than expected.

**Comment by viyer014** [comment]
Interested in working on this! Can I be assigned to this issue?

**Comment by honeycoder96** [comment]
hi @viyer014 ,
Thank you for your interest in contributing to this project.

**Comment by honeycoder96** [comment]
Hi @viyer014 ,
just a friendly reminder to ask if you are still working on this issue.

**Comment by viyer014** [comment]
Hey @honeycoder96 
Yes, I am

**Comment by honeycoder96** [comment]
No issue :)
Thanks

**Comment by antercepter** [comment]
Is this still actual?

**Comment by honeycoder96** [comment]
Yes it is @antercepter .

**Comment by honeycoder96** [comment]
sure @antercepter .

**Comment by honeycoder96** [comment]
This is resolved i #47 .
Thank you very much for your contribution.
