### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by honeycoder96** [DSC-Galgotias/TechnoJam-Chat#20]
Current Behavior: No Splash Screen

Expected Behavior: Create a splash screen using the image [here](https://github.com/DSC-Galgotias/TechnoJam-Chat/blob/master/res/technojam.jpg)
Also add a circular progess bar which for now just pauses the app at splash screen for 2-3 sec
This will later be used for performing the backgound sync.

**Comment by johnnybigoode** [comment]
Hey! I'd like to take a shot at this, is that ok?

**Comment by srivmanu** [comment]
Hey, I'd like to give this a try, would that be ok with the dev?

**Comment by honeycoder96** [comment]
Hi @johnnybigoode ,
Thanks for your interest in contributing to this repository.
You can work on this issue.

**Comment by honeycoder96** [comment]
hi @srivmanu ,
Thank you for your interest in contributing to this repository.
As @johnnybigoode is already working on it I think there is no point in working on the same issue so you can either other issue listed or find and repost a new issue to work upon.

**Comment by honeycoder96** [comment]
hi @johnnybigoode ,
Just a friendly reminder.
Are you still working on this issue.

**Comment by johnnybigoode** [comment]
Nope, I'm not. I'm sorry tried to bite more than what I could chew.

**Comment by honeycoder96** [comment]
No issues @johnnybigoode ,
@srivmanu would you like to take it up?

**Comment by IstiaqueSiddiqi** [comment]
Hi @honeycoder96 ,

Is this issue #19 & #20 open...interested to work on it....can you assign it to me.

**Comment by honeycoder96** [comment]
Hi @IstiaqueSiddiqi ,
You can work on the #20 issue for now but I would like to give @viyer094 to work on #19 .

Thank you for your interest in contributing to this project.

**Comment by honeycoder96** [comment]
This issue has been resolved in #35 

Thank you for your interest.
