### ISSUE TITLE
On boarding Screen

### ISSUE THREAD

**Issue by honeycoder96** [DSC-Galgotias/TechnoJam-Chat#21]
Current Behaviour: When user signup for a new account after clicking the signup button a toast is displayed asking users to verify the mail account and the same activity remains in focus.

Expected Behaviour: once the verification request in send , replace the toast message with a onboarding screen. Use [this](https://www.youtube.com/watch?v=aLErFYrvkeE) video for help.

Additional Detail: On the last screen give the user option to open the email app(not just Gmail) using intent and redirect the app to login activity.

Please don't forget to read the contributors.md file befre making a pull request.

**Comment by muhrahmatullah** [comment]
Hey, anybody already working on this issue? if no, can I take it ? ow yeah, I am also a dsc lead from Indonesia

**Comment by muhrahmatullah** [comment]
@honeycoder96 ok great, regarding the assets like image or else, do you have some? or should I provide it by myself?

**Comment by honeycoder96** [comment]
HI @muhrahmatullah ,
You can use some random placeholder images/gif for now which you feel suitable for this particular application.

**Comment by honeycoder96** [comment]
hi @muhrahmatullah ,
Just a friendly reminder to ask if you are still working on this issue.

**Comment by muhrahmatullah** [comment]
@honeycoder96 yes, I will make the pull request soon it's done, thank you for your reminder

**Comment by honeycoder96** [comment]
No issues @muhrahmatullah  ;)

**Comment by muhrahmatullah** [comment]
Hi, this #34 resolved this issue, thanks

**Comment by honeycoder96** [comment]
Thanks for your contribution :)
