### ISSUE TITLE
Thumbnail image not visible on chat and all user screen

### ISSUE THREAD

**Issue by honeycoder96** [DSC-Galgotias/TechnoJam-Chat#23]
Current behavious : whenever user updates his/profile picture the image is updated on his profile page but it is not visible in other activities like the chat activity, all jsers activity .

Note : when ever an profile image is updated 2 instance of the same is updated in storage 
1. First inside the /profile_image  which is the origin size image
2. Secound inside /profile_images/thumbs which r compressed images

Expected behavious : use the images inside the /profile_ images/thumbs to display on the chat and other activities.

Dont forget to read the contributors.md file before making a pull request.
If u want to work with actuall Firebase console linked with this project  join the slack or whatsapp channel and ask for the console access.

**Comment by mohak1283** [comment]
Working on this

**Comment by honeycoder96** [comment]
sure :) @mohak1283 .
