### ISSUE TITLE
Refactoring the BlogActivity

### ISSUE THREAD

**Issue by honeycoder96** [DSC-Galgotias/TechnoJam-Chat#36]
E.x: The mainactivity is composed of 3 fragments: chat, request, friends .

Current Behaviour: BlogActivity is not divided into fragments.

Expected Behaviour: Divide the BlogActivity into 3 fragments(just like mainactivity) : blog, news and events.

**Comment by mohak1283** [comment]
I would like to work on this issue :100:

**Comment by honeycoder96** [comment]
This issue has been resolved in #37 .
Thank you for your contribution.
