### ISSUE TITLE
Include email authentication before creating the account

### ISSUE THREAD

**Issue by honeycoder96** [DSC-Galgotias/TechnoJam-Chat#4]
Current Behaviour: Currently the app allows to register a user with any email without verification.

Expected Behaviour : When user signup for an account firstly it should verify the users account and then proceed further.

Refer to the following youtube [video](https://www.youtube.com/watch?v=6CBlxNhS9Q4)

**Comment by mohak1283** [comment]
I would like to work on this issue

**Comment by honeycoder96** [comment]
hi @mohak1283 ,
 I am glad you decided to work on it.
Just ping me if you need more resource or any other kind of help regarding this.

**Comment by AndresMx35** [comment]
Hi. is this issue has been resolved? If not, can I work on it? Do you want the account verification just like the video, I mean... same UI?

**Comment by honeycoder96** [comment]
hi @AndresMx35 ,
   Thanks for your interest in contributing in contributing to the repository.
But @mohak1283 is already working on it and as I see is very close to completing it.

so I suggest you either checkout #6 issue.
And yes as of now we are not focusing much on UI.

Thank You.

**Comment by AndresMx35** [comment]
Ok @honeycoder96. Let me take a look on #6 and try to do it. :)

**Comment by honeycoder96** [comment]
Hello @mohak1283 and @AndresMx35 ,

I am closing this issue as this has been solved in #8 by @mohak1283 .

Thanks for you efforts.
