### ISSUE TITLE
Add a Navigation Drawer

### ISSUE THREAD

**Issue by honeycoder96** [DSC-Galgotias/TechnoJam-Chat#40]
Current Behaviour: MainActivity Serves as the parent for the BlogActivity and both of them have a menu bar attached to them.

Expected Behavior: Create a Navigation Drawer similar to [this](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDVaeRlFRf9pdf8ewNYFSgytK0geAqUjydoYGeTMMuRg6Y9i3BWw) and attach it to both MainActivity and the BlogActivity.
In the Navigation Drawer add all the features of the menu bar.

Refer [this](https://www.youtube.com/watch?v=mN6kM_1M0cY&t=294s) video for more details about creating a navigation drawer.

## Don't forget to read the contributors.md file before contributing to this repository.

**Comment by nish-d** [comment]
Hi, I would like to work on this.

**Comment by vandanagupta1501** [comment]
hey @honeycoder96, plz give options you want to add in navigation drawer

**Comment by honeycoder96** [comment]
Hi @nish-d you can work on this issue.

Navigation drawer contains profile pic,status of user and other options present in menu bar. i.e events page , account settings page link, log out option, about the app, contributors page.

For now if there r certqin things Which r not present in the app u can either create dummy data and link them or them just with test without any functionality. @vandanagupta1501 .

**Comment by vandanagupta1501** [comment]
is this is still open @honeycoder96 ?

**Comment by honeycoder96** [comment]
This issue has been solved in #46
