### ISSUE TITLE
TechCrunch API Integration

### ISSUE THREAD

**Issue by honeycoder96** [DSC-Galgotias/TechnoJam-Chat#41]
Current Behaviour: There is no data displayed on the NewsFragment.

Expected Behaviour: You [this](https://newsapi.org/s/techcrunch-api) API to display tech news on the NewsFragment.

Refer to [this](https://www.youtube.com/playlist?list=PLaoF-xhnnrRXZ95JGpey0BLF3kIX72wuP) youtube playlist for more details about doing this.

Note: Use of Retrofit/Volley is preferred.

**Comment by Manik1094** [comment]
I would like to work on this issue

**Comment by honeycoder96** [comment]
sure @Manik1094 go for it.

Also dont forget to checkout the leaderboard on [Gof](http://gof.technojam.tech) website

**Comment by honeycoder96** [comment]
This issue has been resolved in #44 .

Thank you.
