### ISSUE TITLE
Update contributors.md file

### ISSUE THREAD

**Issue by honeycoder96** [DSC-Galgotias/TechnoJam-Chat#42]
Current Behaviour: Contribtors.md file only contains steps to contribute.

Expected Behaviour: Add the name and github account link of the contributors in a table format.
Look at [this](https://github.com/dipakkr/A-to-Z-Resources-for-Students/blob/master/CONTRIBUTORS.md) file for more details.

### Don't forget to read the contributors.md file before contributing to this repository.

**Comment by rmoswela** [comment]
i will take this one :-)

**Comment by honeycoder96** [comment]
Sure @rmoswela
