### ISSUE TITLE
Include Phone Authentication using Firebase

### ISSUE THREAD

**Issue by honeycoder96** [DSC-Galgotias/TechnoJam-Chat#6]
Current Behaviour: user can sign up using only the email id

Expected Behaviour: user firebase phone authentication feature to let the user sign up using a phone number.

Note: Don't forget to ask the user to input data like username and email after phone authentication. 

For further refrence  see [this video](https://www.youtube.com/watch?v=N6HBStmDkMQ)

**Comment by ripudaman1320** [comment]
Hi!!..I'm working on this

**Comment by honeycoder96** [comment]
hi @ripudaman1320 ,
 I am glad you decided to contribute to this repository.

Ping me if you require any further support regarding this.

**Comment by honeycoder96** [comment]
hi @Manik1094 ,
As @ripudaman1320 is already working on it I would suggest that we give him some more time to work on this issue.

**Comment by honeycoder96** [comment]
Hi @ripudaman1320 ,
There is no response from your side.
@Manik1094  if you would still like to work on this issue please respond to the thread.

**Comment by Manik1094** [comment]
Yes I would like to work on this

**Comment by honeycoder96** [comment]
ok @Manik1094 ,
you can take up this issue.

**Comment by honeycoder96** [comment]
There seems to be a flaw in the user flow while integrating the phone authentication.
Hense I am closing this issue for now if someone can suggest a better flow by which the this could be made possible feel free to open this issue again.

Thank you for your interest.
