### ISSUE TITLE
User Navigation Flow

### ISSUE THREAD

**Issue by honeycoder96** [DSC-Galgotias/TechnoJam-Chat#9]
Current Behaviour: When a user clicks on Blog in menu item there is no option for going back to MainActivity or say Chat Screen.

Expected Behaviour: Either a back button in navigation bar or a menu entry to navigate back to chats.

**Comment by mohak1283** [comment]
Okay I am working on this issue

**Comment by honeycoder96** [comment]
this issue is solved by @mohak1283 in #10 .
Thanks for your contribution.
